In [1]:
import numpy as np
import random
from miditime.miditime import MIDITime

In [4]:
mymidi = MIDITime(120, 'myfile.mid')

# Create a list of notes. Each note is a list: [time, pitch, attack, duration]
midinotes = [
    # start_beat, frequency (note), attack, duration_in_beats
    [0, 60, 200, 3],  #At 0 beats (the start), Middle C with attack 200, for 3 beats
    [10, 61, 200, 4]  #At 10 beats (12 seconds from start), C#5 with attack 200, for 4 beats
]

In [5]:
# Add a track with those notes
mymidi.add_track(midinotes)

# Output the .mid file
mymidi.save_midi()

(60, 0, 3, 200)
(61, 10, 4, 200)


In [19]:
#data = np.loadtxt("MAPS_sonify.csv", skiprows=1, delimiter=',', usecols=(1,2), converters=)
data = np.genfromtxt("MAPS_sonify.csv", usecols=(1,2,3), delimiter=',', skip_header=1, autostrip=True)

In [34]:
data[data[:, 1] == -9999] = 0  # I need a better replacement, zero temperatures in CA seems odd
data[data[:, 2] == -9999] = np.nanmedian(data, axis=0)
data[:, 0] = np.nan_to_num(data[:, 0])
data[:, 1] = np.nan_to_num(data[:, 1])
data[:, 2] = np.nan_to_num(data[:, 2])

print np.nanmax(data, axis=0)
print np.nanmin(data, axis=0)
print np.nanmean(data, axis=0)
print np.nanmedian(data, axis=0)

#print data[0:5, :]

num_samples = data.shape[0]
print "num_samples", num_samples
print np.sum(data[:, 0]<=100) / (1.0*num_samples)  
print np.sum(data[:, 0]<=1) / (1.0*num_samples) 

# Q
# 80% of the values are zero...
# 85% below 10
# 90% below 100

#data = data / np.max(data, axis=0) # scale to values between 0 and 1
#print np.max(data, axis=0)
#print np.min(data, axis=0)
#print np.mean(data, axis=0)

[ 1.  1.  1.]
[ 0.  0.  0.]
[ 0.00954834  0.01044151  0.55766606]
[ 0.          0.          0.55580866]
num_samples 14610
1.0
1.0


In [33]:
data = data / np.max(data, axis=0) # scale to values between 0 and 1

In [22]:
def mag_to_pitch_tuned(my_midi, value):
    scale_pct = my_midi.linear_scale_pct(0, 1, value)
    # Pick a range of notes. This allows you to play in a key.
    c_major = ['C', 'C#', 'D', 'D#', 'E', 'E#', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'B#']

    #Find the note that matches your data point
    note = my_midi.scale_to_note(scale_pct, c_major)

    #Translate that note to a MIDI pitch
    midi_pitch = my_midi.note_to_midi_pitch(note)

    return midi_pitch

In [30]:
mymidi = MIDITime(120, 't.mid', 2, 4, 1) # 3 seconds per year, 4 as base note, 1 beat duration

In [38]:
min_data_values = {'0':0.001, '1':0.001, '2':0.1} # if value is below this it doesnt produce sound
file_names = {'0':'q.mid', '1':'p.mid', '2':'t.mid'}

for column in range(3):
    notes  = []
    min_data_value = min_data_values[str(column)]
    file_name = file_names[str(column)]
    mymidi = MIDITime(120, file_name, 2, 4, 1)
    for i in range(data.shape[0]):
        data_value = data[i, column]
        if data_value > min_data_value:
            beat = i
            value = mag_to_pitch_tuned(mymidi, data_value)
            attack = random.randint(0,200)
            duration = random.randint(1,4) 
            notes.append([beat, value, attack, duration])
    mymidi.add_track(notes)
    mymidi.save_midi()

(48, 78, 4, 27)
(48, 86, 2, 114)
(48, 87, 3, 65)
(48, 88, 2, 55)
(48, 89, 2, 156)
(48, 90, 4, 124)
(48, 94, 4, 127)
(48, 95, 4, 26)
(48, 96, 2, 18)
(48, 97, 1, 193)
(48, 100, 4, 8)
(48, 101, 4, 8)
(48, 102, 1, 170)
(48, 105, 3, 186)
(48, 106, 2, 129)
(48, 107, 4, 93)
(48, 108, 4, 180)
(48, 109, 2, 62)
(48, 110, 4, 109)
(48, 111, 3, 55)
(48, 120, 2, 143)
(48, 127, 1, 61)
(48, 128, 3, 171)
(48, 129, 2, 6)
(48, 130, 3, 146)
(50, 131, 2, 100)
(51, 132, 3, 57)
(50, 133, 3, 65)
(50, 134, 1, 2)
(49, 135, 2, 96)
(49, 136, 2, 38)
(50, 137, 2, 197)
(49, 138, 3, 194)
(49, 139, 4, 3)
(49, 140, 1, 144)
(48, 141, 1, 127)
(48, 142, 4, 113)
(48, 143, 3, 19)
(48, 144, 2, 59)
(48, 145, 2, 143)
(48, 146, 3, 160)
(48, 147, 3, 20)
(48, 148, 3, 10)
(48, 149, 3, 136)
(48, 150, 2, 0)
(51, 151, 3, 37)
(53, 152, 3, 79)
(52, 153, 1, 119)
(54, 154, 3, 77)
(53, 155, 3, 72)
(51, 156, 4, 12)
(51, 157, 4, 28)
(50, 158, 3, 127)
(50, 159, 2, 171)
(51, 160, 4, 195)
(51, 161, 4, 145)
(51, 162, 2, 87)
(50, 163, 3, 25)
(48

In [32]:
# Add a track with those notes
mymidi.add_track(notes)

# Output the .mid file
mymidi.save_midi()

(59, 0, 4, 124)
(59, 1, 4, 81)
(59, 2, 4, 147)
(59, 3, 3, 0)
(59, 4, 4, 196)
(59, 5, 3, 113)
(59, 6, 3, 154)
(59, 7, 4, 95)
(59, 8, 3, 56)
(59, 9, 4, 101)
(59, 10, 4, 60)
(59, 11, 4, 33)
(59, 12, 2, 39)
(59, 13, 1, 20)
(59, 14, 2, 174)
(59, 15, 2, 164)
(59, 16, 1, 81)
(59, 17, 3, 95)
(59, 18, 1, 185)
(59, 19, 2, 119)
(59, 20, 3, 155)
(59, 21, 3, 15)
(59, 22, 2, 49)
(59, 23, 2, 40)
(59, 24, 4, 119)
(59, 25, 1, 30)
(59, 26, 3, 89)
(59, 27, 4, 87)
(59, 28, 4, 85)
(59, 29, 3, 116)
(59, 30, 1, 45)
(59, 31, 3, 97)
(59, 32, 4, 15)
(59, 33, 2, 38)
(59, 34, 3, 41)
(59, 35, 1, 9)
(59, 36, 2, 64)
(59, 37, 1, 63)
(59, 38, 4, 106)
(59, 39, 3, 133)
(59, 40, 4, 198)
(59, 41, 3, 78)
(59, 42, 1, 78)
(59, 43, 4, 45)
(59, 44, 3, 3)
(59, 45, 3, 32)
(59, 46, 3, 28)
(59, 47, 3, 161)
(59, 48, 2, 156)
(59, 49, 2, 144)
(59, 50, 1, 86)
(59, 51, 3, 93)
(59, 52, 4, 158)
(59, 53, 3, 57)
(59, 54, 1, 60)
(59, 55, 1, 106)
(59, 56, 3, 153)
(59, 57, 1, 144)
(59, 58, 1, 53)
(59, 59, 3, 187)
(59, 60, 3, 188)
(59, 61, 1, 